### ISSUE TITLE
Upgrading to ANTLR 4

### ISSUE THREAD

**Issue by KvanTTT** [porcelli/plsql-parser#27]
I translated this grammar to ANTLR 4 and upload it to official rep: https://github.com/antlr/grammars-v4/tree/master/plsql

**Comment by TheSnoozer** [comment]
You currently can't build the current version with java 8 and therefore upgrading sounds reasonable 

see https://github.com/antlr/antlr3/issues/151

**Comment by KvanTTT** [comment]
Done: https://github.com/antlr/grammars-v4/tree/master/plsql
